Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -102,18 +102,18 @@ jobs:
           ls -l
           cat sbom-result.txt || echo "sbom-result.txt not found"
 
-      - name: Run Trivy Scan
-        run: |
-          bash ./trivy.sh
-          echo "After trivy.sh:"
-          ls -l
-          cat trivy-vulnerabilities.txt || echo "trivy-vulnerabilities.txt not found"
+      # - name: Run Trivy Scan
+      #   run: |
+      #     bash ./trivy.sh
+      #     echo "After trivy.sh:"
+      #     ls -l
+      #     cat trivy-vulnerabilities.txt || echo "trivy-vulnerabilities.txt not found"
 
-      - name: Upload Trivy Vulnerabilities
-        uses: actions/upload-artifact@v4
-        with:
-          name: trivy-vulnerabilities
-          path: trivy-vulnerabilities.txt
+      # - name: Upload Trivy Vulnerabilities
+      #   uses: actions/upload-artifact@v4
+      #   with:
+      #     name: trivy-vulnerabilities
+      #     path: trivy-vulnerabilities.txt
 
       - name: Upload SBOM Result
         uses: actions/upload-artifact@v4
